const chai = require('chai')
const sinon = require('sinon')
const sinonChai = require('sinon-chai')
const {describe, it} = require('mocha')
const { getAllVillains, getVillainBySlug, saveNewVillain } = require('../../controller/villains.js')